### ISSUE TITLE
Suggestions: Could you add an overload to the isValidV4Uuid function that accepts a string representation

### ISSUE THREAD

**Issue by ellogwen** [protohaus/ESPRandom#3]
I just need to check if a uuidv4, that I receive as a string, is a valid uuidv4. ESPRandom conveniently has a check function for that, but sadly i first need to convert the string into a vector or buffer to utilize this function.

Maybe you could add an overload that accepts a string and does the convertion for the user.

**Comment by moritz89** [comment]
Hi @ellogwen, I have moved to a different implementation of the UUID library. I have just extracted it into a new library [ESP UUID](https://github.com/protohaus/ESP_UUID) from my [sdg-controller](https://github.com/protohaus/sdg-controller) firmware which covers this use case. Perhaps it will be useful to you. I will not be doing any more dev work for this implementation, but will accept pull requests if they are made.
